language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip
before_install:
  - travis_retry go get github.com/mattn/goveralls
script:
  - travis_retry go test -v
  - travis_retry $HOME/gopath/bin/goveralls -service=travis-ci
